app_id =
app_key = ""
# 识别模型，比如普通话还是英语，是否要加标点等
# 1537	中文普通话	无标点
# 15372	中文普通话	加强标点（逗号、句号、问号、感叹号）
# 1737	英语	无标点
# 17372	英语	加强标点（逗号、句号、问号）
dev_pid =
# 统计UV使用，发起请求设备的唯一id，如服务器的mac地址。随意填写不影响识别结果。长度128个字符内，即[a-zA-Z0-9-_]{1, 128}
cuid = ""
# pcm , 固定格式
format = "pcm"
# 16000， 固定采样率
sample = 16000