[bd_tts_conf]
url = ""
# 语言选择,填写zh，表示中文合成请求
lan = "zh"
# 客户端类型选择10，web端填写1
ctp = 1
# 产品ID对应的key，邮件申请，由语音合成接口人分配，与pdt一一对应
key = ""
# 用户唯一标识，用来区分用户，填写机器 MAC 地址或 IMEI 码，长度为60以内
cuid =  "test"
# 音调，取值0-15，默认为5中语调
pit = 6
# 语速，取值0-15，默认为5中语速
spd = 5
# 音量，取值0-15，默认为5中音量
vol = 5
# 产品ID(PID)，邮件申请，由语音合成接口人分配
pdt = 323
# 音频编码格式（2: opus; 3：mp3；4：pcm；5：pcm-8k（callcenter专用）；6：wav；）。web请求默认为mp3，SDK请求默认为opus
aue = 6
# 发音人选择, 默认为普通女声，其他参考下面的发音人列表
# 标准女生	       0
# 标准男生	       1
# 度逍遥            3
# 度小雯(鸽子）	   100
# 度米朵	           103
# 度博文	           106
# 度小希            5117
# 度小乔            4117
per = 4117
